repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-json
      - id: check-toml
      - id: check-xml
      - id: debug-statements
      - id: check-docstring-first

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.0
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format

  - repo: local
    hooks:
      - id: pyright-check
        name: pyright-check
        entry: uv run pyright
        language: system
        pass_filenames: false
        always_run: true
        verbose: true

  - repo: local
    hooks:
      - id: pytest-check
        name: pytest-check
        entry: uv run pytest --tb=short tests/test_models.py
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-push]
